version: "2"

services:
  samba:
    image: dperson/samba
    environment:
        - TZ=America/Argentina/Buenos_Aires
    restart: always
    command: '-u "usuario;password" -s "tl3;/tl3;yes;no;no" -S'
    stdin_open: true
    tty: true
    ports:
        - 139:139
        - 445:445     
    
    volumes:
      - ${PWD}:/tl3
    
